import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import { SecuritiesProvider } from './components/StockSearch'
import './tokens.css'
import './reset-and-shell.css'
import './components.css'
import './libraries.css'
import './workbench.css'
import './conversation.css'
import './usability.css'
import './news.css'
import './observation.css'
import './visual-polish.css'
import './research-projects.css'
import './page-experience.css'
import './workspace-redesign.css'
import './research-redesign.css'
import './library-redesign.css'
import './conversation-redesign.css'
import './condition-workflow.css'
import './condition-studio.css'
import './screening-conversation.css'
import './observation-redesign.css'
import './news-reading-polish.css'
import './experience-polish.css'
import './task-progress.css'
import './task-guidance.css'
import './chat-layout.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <SecuritiesProvider><App /></SecuritiesProvider>
  </React.StrictMode>,
)
